### ISSUE TITLE
Unable to use with sqs

### ISSUE THREAD

**Issue by grapemix** [3stack-software/celery-cloudwatch#7]
Hi,
Thanks for this lib. I tried to use this lib with sqs. I am sure my sqs is working because I can send_message thru boto and I can run debug_task in django's shell. 

Here is my env:

Ubuntu 16.04 in aws
Using sqs

Here is my yaml:

ccwatch:
  broker: "sqs://"
  camera: celery_cloudwatch.CloudWatchCamera
  verbose: no
camera:
  frequency: 60.0
  verbose: no
cloudwatch-camera:
  dryrun: no
  namespace: celery
  tasks:
    - BUNCH_OF_TASK

Here is the traceback when I run manually as root:
Traceback (most recent call last):
  File "/usr/local/bin/ccwatch", line 9, in <module>
    load_entry_point('celery-cloudwatch==1.1.1', 'console_scripts', 'ccwatch')()
  File "/PATH/local/lib/python2.7/site-packages/celery_cloudwatch/__main__.py", line 78, in main
    monitor.run()
  File "/PATH/local/lib/python2.7/site-packages/celery_cloudwatch/task_monitor.py", line 38, in run
    recv.capture(limit=None, timeout=None, wakeup=False)
  File "/PATH/local/lib/python2.7/site-packages/celery/events/receiver.py", line 93, in capture
    return list(self.consume(limit=limit, timeout=timeout, wakeup=wakeup))
  File "/PATH/local/lib/python2.7/site-packages/kombu/mixins.py", line 192, in consume
    conn.drain_events(timeout=safety_interval)
  File "/PATH/local/lib/python2.7/site-packages/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/PATH/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 961, in drain_events
    get(self._deliver, timeout=timeout)
  File "/PATH/local/lib/python2.7/site-packages/kombu/utils/scheduling.py", line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/PATH/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 999, in _drain_channel
    return channel.drain_events(callback=callback, timeout=timeout)

Any ideas? BTW, will this lib switch to boto3 in the future?

Thanks.

**Comment by nathan-muir** [comment]
Hi @grapemix 

[Task events are not supported for Celery on SQS](http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html)

For celery cloudwatch (or any other celery monitoring tool) to work, we need access to the task events. These events are signals like "task sent", "task started", "task failed" etc.
